name: Code Linters
on:
  pull_request:
    branches:
      - develop
      - main
  push:
    branches:
      - develop
      - main

jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install clang-format make
      - name: Checkout code
	uses: actions/checkout@v2

      - name: clang-format
        shell: bash
        run: |
          make clang-format
          git status --porcelain
          git diff --exit-code

